/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'vensivat' at '3/14/16 4:32 PM' with Gradle 2.9
 *
 * @author vensivat, @date 3/14/16 4:32 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
